openapi: 3.0.1
info:
  title: Checkout Service API
  version: 1.0.0
paths:
  /v1/checkout/initiate:
    post:
      summary: Initiates the checkout process and creates a payment intent.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                cartItems:
                  type: array
                  items:
                    type: object
                    properties:
                      sku: { type: string }
                      quantity: { type: integer }
                shippingAddress: { type: object }
      responses:
        '201':
          description: Successfully created order and payment intent.
          content:
            application/json:
              schema:
                type: object
                properties:
                  orderId: { type: string, format: uuid }
                  clientSecret: { type: string }
        '400':
          description: Bad request (e.g., invalid SKU, item out of stock).

  /v1/webhooks/payment-provider:
    post:
      summary: Inbound webhook for payment provider status updates (e.g., Stripe).
      description: This endpoint is called by the external payment provider, not the frontend.
      requestBody:
        description: The event payload from the payment provider.
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Webhook received and acknowledged.
        '400':
          description: Invalid webhook signature or payload.
